name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Build and Deploy
      uses: TanametTpk/kaptuer-backend-app@master
      with:
        ACCESS_TOKEN: ${{secrets.github_workflow}}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
    # - name: Deploy to GH Pages
    #   run: |
    #     git config --global user.email "tanamet.tpk@gmail.com"
    #     git config --global user.name "TanametTpk"
    #     git remote set-url origin https://tanamettpk:${GITHUB_TOKEN}@github.com/TanametTpk/kaptuer-backend-app.git
    #     npm run deploy
    #   env:
    #     GITHUB_TOKEN: ${{secrets.github_workflow}}
