name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "tanamet.tpk@gmail.com"
        git config --global user.name "TanametTpk"
        git remote set-url origin https://TanametTpk:f3baa7b2e1c332e2d2d2a7ea43a1de68a6dd5f6a@github.com/TanametTpk/kaptuer-backend-app.git
        npm run deploy